### ISSUE TITLE
请教关于libMM.a的一个问题

### ISSUE THREAD

**Issue by BNUphyKLiang** [wanderxu/dqmc_demo#1]
您好当我在lib文件夹中按readme中步骤操作以后似乎系统没找到  libMM.a 在网络上没找到libMM的有关信息
 当我再次make的时候出现以下提示：
ar -ruv libMM.a m_constants.o m_spring.o 还有其他一些.o文件 
请问这是成功了吗？
另外在src文件夹中make的时候出现
很多undefined reserence to'   '
例如：dgebal.f:(.text+0x67b):  undefined reserence to' dnrm2_  '
最后还有
collect2:error: ld returned 1 exit status
make: ***[ftdqmc] Error 1

**Comment by wanderxu** [comment]
First please check that libMM.a is complied sucessfully. You will see a file libMM.a after you compile the lib.
Second, please check that you have already installed lapack and blas and linked them in the right way.
If both are checked, and you still have the issue, please send me more details.

**Comment by BNUphyKLiang** [comment]
I did installed lapack and blas 3.8.0
but I did not link them .I am new to Linux, could you please tell me how to linked them?

I find that when I make in the src , it seems that the  program think the directory of 'dnrm2' is xxxx lapack xxx. (Shows in the picture
![pic](https://user-images.githubusercontent.com/45036086/48531307-b7da9100-e8d6-11e8-8234-e6d086a19345.PNG)
)
However when I check lapack-3.8.0 I did not find ' dnrm2' but I find it in blas-3.8.0. 
Then I try to copy these *.o from blas to lapack . and vi Makefile in the lapack to add these *.o in lapack . But somehow I failed. So I think maybe the method is wrong.

**Comment by wanderxu** [comment]
I want to know whether your problem has been soloved.
Make sure you have add the path of lapack and blas to LD_LIBBRARY_PATH. You should not change Makefile. The compling setup is in the file make.sys.

**Comment by BNUphyKLiang** [comment]
I have copied liblapack.a and librefblas.a and libtmglib.a  to /usr   and /usr/lib and   /usr/local/lib do I still have to add the path to LD_LIBBRARY_PATH?

**Comment by wanderxu** [comment]
The default setup uses dynamic linking. So you should copy .so files instead .a files.

**Comment by wanderxu** [comment]
The default setup expects files with names libblas.a and liblapack.a. Can you attach your make.sys file?

**Comment by BNUphyKLiang** [comment]
I did not change the make.sys in src or lib
[make.sys.zip](https://github.com/wanderxu/dqmc_demo/files/2583790/make.sys.zip)
after I download I first compiled lib
then did(in src):
cp make.sys.gfortran make.sys
make
maybe I did wrong I will try agin

Is it because I did not delete 
#machine tuning options, just for my laptop

?

**Comment by wanderxu** [comment]
Good. Then the only thing you need is to install blas and lapack, and you will have libblas.a and liblapack.a. Sometimes, if you do not have the right name, you should define a link, for example, ln -sf librefblas.a libblas.a.

**Comment by BNUphyKLiang** [comment]
It worked thank you very much!
So now I can use the *.sh in example？

**Comment by wanderxu** [comment]
Yes. It is better to first have a look inside those .sh files.

**Comment by BNUphyKLiang** [comment]
I vi the cal_para.sh and find it hard to understand the parameters is there any help doc just like the projiect simpleDQMC or I can chek them in the program?

**Comment by wanderxu** [comment]
most of the parameters are already mentioned in the readme.

**Comment by BNUphyKLiang** [comment]
OK thanks again!
